export type CellState = "yes" | "partial" | "no";

export type EvidenceCell = {
  state: CellState;
  note: string;
};

export type MatrixRow = {
  paper: string;
  venue: string;
  url: string;
  cells: Record<string, EvidenceCell>;
};

export type PaperDossier = {
  id: string;
  title: string;
  venue: string;
  year: number;
  honor?: string;
  branch: "前馈几何" | "动态 4D" | "持久记忆" | "3D 生成分布" | "物理世界模型";
  relation: "直接继承" | "表征继承" | "问题延续" | "相邻参照";
  buildsOn: string;
  unique: string;
  evidence: string;
  limitation: string;
  readNext: string;
  url: string;
};

const e = (state: CellState, note: string): EvidenceCell => ({ state, note });

export const geometryColumns = [
  { key: "global3d", label: "全局 3D", group: "任务" },
  { key: "dynamic", label: "动态对应", group: "任务" },
  { key: "future", label: "未来预测", group: "任务" },
  { key: "nview", label: "N 视图联合", group: "功能" },
  { key: "metric", label: "度量尺度", group: "功能" },
  { key: "memory", label: "流式记忆", group: "功能" },
  { key: "query", label: "任意查询", group: "功能" },
  { key: "multi", label: "多解分布", group: "不确定性" },
] as const;

export const geometryMatrix: MatrixRow[] = [
  {
    paper: "DUSt3R",
    venue: "CVPR 2024",
    url: "https://openaccess.thecvf.com/content/CVPR2024/html/Wang_DUSt3R_Geometric_3D_Vision_Made_Easy_CVPR_2024_paper.html",
    cells: {
      global3d: e("yes", "一对图像的两张 pointmap 都落在相机 1 坐标系。"),
      dynamic: e("no", "表征与训练假设静态场景。"),
      future: e("no", "只重建已观测图像，不外推未来。"),
      nview: e("partial", "多于两视图时仍需全局对齐优化。"),
      metric: e("no", "训练与输出采用尺度归一化，只有相对尺度。"),
      memory: e("no", "成对处理，没有跨帧持久状态。"),
      query: e("no", "固定输出两张稠密 pointmap。"),
      multi: e("no", "确定性回归；同一输入只给一个几何答案。"),
    },
  },
  {
    paper: "MASt3R",
    venue: "ECCV 2024",
    url: "https://arxiv.org/abs/2406.09756",
    cells: {
      global3d: e("yes", "保留 DUSt3R 的共同坐标 pointmap。"),
      dynamic: e("no", "新增的是匹配描述子，不是动态表征。"),
      future: e("no", "没有时间外推目标。"),
      nview: e("partial", "匹配更准，但全局重建仍依赖对齐流程。"),
      metric: e("no", "没有解决绝对尺度。"),
      memory: e("no", "仍以图像对为基本单元。"),
      query: e("partial", "可快速查询互惠匹配，但不能查询任意 4D 射线。"),
      multi: e("no", "点图和描述子均为确定性预测。"),
    },
  },
  {
    paper: "Spann3R",
    venue: "3DV 2025",
    url: "https://arxiv.org/abs/2408.16061",
    cells: {
      global3d: e("yes", "每个新帧直接读出到统一世界坐标。"),
      dynamic: e("no", "空间记忆按静态世界设计。"),
      future: e("no", "只整合已到达的帧。"),
      nview: e("yes", "工作记忆与长期记忆在线整合多帧。"),
      metric: e("no", "仍是相对尺度重建。"),
      memory: e("yes", "核心贡献就是可更新的外部空间记忆。"),
      query: e("partial", "从记忆读出当前帧，但不能任意时间/相机查询。"),
      multi: e("no", "记忆读出是单点估计。"),
    },
  },
  {
    paper: "MonST3R",
    venue: "ICLR 2025",
    url: "https://monst3r-project.github.io/",
    cells: {
      global3d: e("yes", "视频优化把每帧点图对齐到全局。"),
      dynamic: e("partial", "能重建动态深度，但对应关系依赖外部光流。"),
      future: e("no", "只解释输入视频。"),
      nview: e("partial", "通过滑窗和全局优化融合，而非一次联合前馈。"),
      metric: e("no", "结果仍需尺度对齐。"),
      memory: e("no", "没有持久状态。"),
      query: e("no", "固定帧级点图输出。"),
      multi: e("no", "确定性点图与优化。"),
    },
  },
  {
    paper: "Dynamic Point Maps",
    venue: "ICCV 2025",
    url: "https://openaccess.thecvf.com/content/ICCV2025/html/Sucar_Dynamic_Point_Maps_A_Versatile_Representation_for_Dynamic_3D_Reconstruction_ICCV_2025_paper.html",
    cells: {
      global3d: e("yes", "四张 pointmap 共享同一相机与时间参考。"),
      dynamic: e("yes", "同一物理点在两个时间的坐标差直接给 scene flow。"),
      future: e("no", "跨时间预测限于两张已观测图像的时间戳。"),
      nview: e("partial", "原论文仍是两视图，更多视图需后处理。"),
      metric: e("no", "未解决绝对尺度。"),
      memory: e("no", "没有流式状态。"),
      query: e("partial", "可选择两个已知时间参考，但不是任意连续查询。"),
      multi: e("no", "四张图仍是确定性回归。"),
    },
  },
  {
    paper: "St4RTrack",
    venue: "ICCV 2025",
    url: "https://arxiv.org/abs/2504.13152",
    cells: {
      global3d: e("yes", "重建与跟踪 pointmap 都在首帧世界坐标。"),
      dynamic: e("yes", "同一时刻的双 pointmap 同时提供重建和长程跟踪。"),
      future: e("no", "处理的是已观测帧。"),
      nview: e("partial", "首帧与每个后续帧成对链式处理。"),
      metric: e("no", "评测前使用中值尺度对齐。"),
      memory: e("no", "没有递归持久状态。"),
      query: e("no", "固定跟踪/重建头。"),
      multi: e("no", "确定性输出。"),
    },
  },
  {
    paper: "CUT3R",
    venue: "CVPR 2025",
    url: "https://openaccess.thecvf.com/content/CVPR2025/html/Wang_Continuous_3D_Perception_Model_with_Persistent_State_CVPR_2025_paper.html",
    cells: {
      global3d: e("yes", "持续状态让所有读出共享世界坐标。"),
      dynamic: e("partial", "可处理视频变化，但未显式输出 scene flow 或时间不变对应。"),
      future: e("no", "虚拟视图补全是空间外推，不是未来动力学。"),
      nview: e("yes", "逐帧更新统一状态，无需全局对齐。"),
      metric: e("yes", "直接预测度量 pointmap 与相机。"),
      memory: e("yes", "state update / readout 是论文的核心。"),
      query: e("yes", "raymap 可查询未观测虚拟视角。"),
      multi: e("no", "作者明确指出确定性回归会使外推几何模糊。"),
    },
  },
  {
    paper: "VGGT",
    venue: "CVPR 2025 · Best Paper",
    url: "https://openaccess.thecvf.com/content/CVPR2025/html/Wang_VGGT_Visual_Geometry_Grounded_Transformer_CVPR_2025_paper.html",
    cells: {
      global3d: e("yes", "相机、深度与点图在一个全局前馈模型中联合预测。"),
      dynamic: e("no", "论文明确说明主模型不是为动态场景设计。"),
      future: e("no", "没有未来状态目标。"),
      nview: e("yes", "交替 frame/global attention 一次处理 1 到数百视图。"),
      metric: e("partial", "全局几何一致，但仍存在整体尺度不确定性。"),
      memory: e("no", "整组输入一次编码，不是流式持久状态。"),
      query: e("partial", "有跟踪查询，但几何主体仍由多个专用稠密头输出。"),
      multi: e("no", "同一输入给单一重建。"),
    },
  },
  {
    paper: "π³",
    venue: "ICLR 2026",
    url: "https://arxiv.org/abs/2507.13347",
    cells: {
      global3d: e("partial", "不设固定世界锚点；预测局部 pointmap 与仿射不变相机，再做对齐解释。"),
      dynamic: e("no", "目标仍是视觉几何，不显式建模物体运动。"),
      future: e("no", "没有时间预测。"),
      nview: e("yes", "架构对视图置换等变。"),
      metric: e("no", "局部点图尺度不变、相机仿射不变。"),
      memory: e("no", "一次处理视图集合。"),
      query: e("no", "固定几何输出。"),
      multi: e("no", "仍是确定性前馈回归。"),
    },
  },
  {
    paper: "MapAnything",
    venue: "3DV 2026",
    url: "https://map-anything.github.io/",
    cells: {
      global3d: e("yes", "局部深度/射线/相机通过全局尺度组合成统一坐标。"),
      dynamic: e("no", "作者把 scene flow 列为未来工作。"),
      future: e("no", "没有动力学外推。"),
      nview: e("yes", "同一 Transformer 支持任意视图数与输入组合。"),
      metric: e("yes", "显式预测全局 metric scale factor。"),
      memory: e("no", "没有持续更新的场景记忆。"),
      query: e("partial", "输入模态很灵活，但输出仍是一对一稠密解码。"),
      multi: e("no", "论文明确未建模输入噪声或不确定性。"),
    },
  },
  {
    paper: "V-DPM",
    venue: "CVPR 2026",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Sucar_V-DPM_4D_Video_Reconstruction_with_Dynamic_Point_Maps_CVPR_2026_paper.html",
    cells: {
      global3d: e("yes", "视频内时间变/时间不变 pointmap 共享首相机坐标。"),
      dynamic: e("yes", "直接恢复每个像素的 3D 运动，不需额外光流。"),
      future: e("no", "目标时间来自输入视频片段，不预测未观测未来。"),
      nview: e("yes", "把两视图 DPM 扩展到 VGGT 的视频级多视图。"),
      metric: e("no", "采用单位平均距离尺度。"),
      memory: e("no", "整段视频一次处理；长视频仍用窗口融合。"),
      query: e("yes", "时间条件 decoder 可读出给定目标时间的点图。"),
      multi: e("no", "确定性 DPM 预测。"),
    },
  },
  {
    paper: "DynamicVGGT",
    venue: "CVPR 2026",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/He_DynamicVGGT_Learning_Dynamic_Point_Maps_for_4D_Scene_Reconstruction_in_CVPR_2026_paper.html",
    cells: {
      global3d: e("yes", "当前/未来 pointmap 在 VGGT 学得的共同 canonical frame。"),
      dynamic: e("yes", "MTA、future point head 与高斯速度联合建模运动。"),
      future: e("yes", "短片内显式预测同相机未来 pointmap。"),
      nview: e("yes", "继承 VGGT 的多视图交替注意力。"),
      metric: e("partial", "主要保持 VGGT 几何先验，未以统一绝对尺度为主张。"),
      memory: e("no", "短 clip 联合处理，无持久状态。"),
      query: e("no", "依赖未来点头和 3DGS 头，而非统一查询。"),
      multi: e("no", "未来点和速度是单一回归。"),
    },
  },
  {
    paper: "Any4D",
    venue: "CVPR 2026",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Karhade_Any4D_Unified_Feed-Forward_Metric_4D_Reconstruction_CVPR_2026_paper.html",
    cells: {
      global3d: e("yes", "allocentric 相机/scene flow 与 egocentric 深度共同定义 4D。"),
      dynamic: e("yes", "输出稠密世界坐标 scene flow。"),
      future: e("no", "输出输入帧间运动，不外推未观测未来。"),
      nview: e("yes", "N 帧一次前馈。"),
      metric: e("yes", "显式预测 metric scale，并可利用 RGB-D/IMU/Radar。"),
      memory: e("no", "不是流式模型。"),
      query: e("no", "多专用 decoder 直接输出固定因子。"),
      multi: e("no", "确定性回归；没有多未来采样。"),
    },
  },
  {
    paper: "Point4Cast",
    venue: "CVPR 2026",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Liu_Point4Cast_Streaming_Dynamic_Scene_Reconstruction_and_Forecasting_CVPR_2026_paper.html",
    cells: {
      global3d: e("yes", "时间条件 pointmap 从同一 latent spacetime 读出。"),
      dynamic: e("yes", "不同查询时刻的点图差直接给 scene flow。"),
      future: e("yes", "首次把未观测未来 pointmap forecast 作为核心任务。"),
      nview: e("yes", "新帧持续更新同一状态。"),
      metric: e("partial", "主要基准使用尺度对齐的点图误差。"),
      memory: e("yes", "4096 token 的持久 spacetime state。"),
      query: e("yes", "可给定已见 query frame 与任意过去/现在/未来时间。"),
      multi: e("no", "论文结尾明确把 uncertainty modeling 留作未来工作。"),
    },
  },
  {
    paper: "D4RT",
    venue: "CVPR 2026 · Best Paper",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Zhang_Efficiently_Reconstructing_Dynamic_Scenes_One_D4RT_at_a_Time_CVPR_2026_paper.html",
    cells: {
      global3d: e("yes", "全视频 latent 为所有 4D ray query 提供共同上下文。"),
      dynamic: e("yes", "源/目标时间查询直接得到跨时 3D 对应。"),
      future: e("no", "t_src/t_tgt 位于输入视频；不是未观测动力学预测。"),
      nview: e("yes", "全视频编码器提供全局上下文。"),
      metric: e("partial", "统一坐标很强，但论文核心不是绝对 metric scale。"),
      memory: e("no", "一次编码完整视频，不是可持续更新的在线状态。"),
      query: e("yes", "一个轻量 decoder 接受 (u,v,t_src,t_tgt,t_cam) 查询。"),
      multi: e("no", "每个 query 返回单一 3D 点；无概率/多假设头。"),
    },
  },
];

export const distributionColumns = [
  { key: "native", label: "原生 3D/4D 状态", group: "状态" },
  { key: "explicit", label: "显式多解采样", group: "分布" },
  { key: "across", label: "跨场景先验", group: "分布" },
  { key: "action", label: "动作 / 变换条件", group: "交互" },
  { key: "memory", label: "持久 belief / memory", group: "交互" },
  { key: "geometry", label: "几何监督 / 约束", group: "证据" },
  { key: "closed", label: "闭环 / 控制证据", group: "证据" },
] as const;

export const distributionMatrix: MatrixRow[] = [
  {
    paper: "LRM",
    venue: "2023",
    url: "https://arxiv.org/abs/2311.04400",
    cells: {
      native: e("yes", "直接预测 triplane-NeRF。"),
      explicit: e("no", "作者明确称其为 deterministic；遮挡区出现 mode averaging 模糊。"),
      across: e("yes", "在约 100 万对象上学习共享 3D prior。"),
      action: e("no", "单图对象重建。"),
      memory: e("no", "没有时序状态。"),
      geometry: e("yes", "多视图可微渲染监督。"),
      closed: e("no", "没有控制实验。"),
    },
  },
  {
    paper: "MVDream",
    venue: "ICLR 2024",
    url: "https://proceedings.iclr.cc/paper_files/paper/2024/file/adbe936993aa7cf41e45054d8b72f183-Paper-Conference.pdf",
    cells: {
      native: e("partial", "概率分布在相机条件多视图图像上；3D 资产仍经 SDS 优化。"),
      explicit: e("yes", "扩散模型可从同一文本采样不同多视图集合。"),
      across: e("yes", "混合 2D 文图与 3D 渲染数据学习 prior。"),
      action: e("partial", "相机视角受控，但没有物理动作。"),
      memory: e("no", "固定多视图生成。"),
      geometry: e("partial", "由相机标注和跨视图注意力约束，未直接生成原生 3D latent。"),
      closed: e("no", "无闭环控制。"),
    },
  },
  {
    paper: "TRELLIS",
    venue: "CVPR 2025 · Highlight",
    url: "https://trellis3d.github.io/",
    cells: {
      native: e("yes", "SLAT 是稀疏 3D 网格上的局部结构/外观 latent。"),
      explicit: e("yes", "两阶段 rectified flow 采样稀疏结构与局部 latent。"),
      across: e("yes", "在 50 万 3D 资产上训练最高 2B 模型。"),
      action: e("partial", "支持文本/图像条件与局部编辑，不是动力学动作。"),
      memory: e("no", "资产级一次生成。"),
      geometry: e("yes", "直接编码原生 3D 资产，可解码 RF/3DGS/mesh。"),
      closed: e("no", "无代理闭环。"),
    },
  },
  {
    paper: "O-Voxel",
    venue: "CVPR 2026 · Best Student Paper",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Xiang_Native_and_Compact_Structured_Latents_for_3D_Generation_CVPR_2026_paper.html",
    cells: {
      native: e("yes", "O-Voxel 同时编码复杂拓扑、几何与 PBR 材质。"),
      explicit: e("yes", "4B flow-matching 模型在压缩 3D latent 上采样。"),
      across: e("yes", "来自多套大规模 3D 资产数据。"),
      action: e("partial", "图像/形状条件，不是物理动作序列。"),
      memory: e("no", "单资产生成。"),
      geometry: e("yes", "原生 mesh↔O-Voxel 转换与重建消融直接验证。"),
      closed: e("no", "没有控制任务。"),
    },
  },
  {
    paper: "FlashWorld",
    venue: "ICLR 2026 · Oral",
    url: "https://arxiv.org/abs/2510.13678",
    cells: {
      native: e("yes", "3D-oriented 模式在多视图去噪过程中直接产生 3D Gaussian。"),
      explicit: e("yes", "扩散/分布匹配蒸馏保留随机生成分布。"),
      across: e("yes", "多视图数据外加单图/文本 OOD 共训。"),
      action: e("partial", "文本、图像与相机轨迹条件；无物理动力学。"),
      memory: e("no", "静态场景一次生成。"),
      geometry: e("yes", "3D-oriented 模式保证渲染来自同一 3DGS。"),
      closed: e("no", "无控制实验。"),
    },
  },
  {
    paper: "Geometry Forcing",
    venue: "ICLR 2026",
    url: "https://arxiv.org/abs/2507.07982",
    cells: {
      native: e("partial", "主体仍是视频 latent，但中间特征可解码显式几何。"),
      explicit: e("yes", "保留视频 flow/diffusion 的采样分布。"),
      across: e("yes", "视频生成器从数据学习跨场景动态 prior。"),
      action: e("yes", "同时在相机条件与 Minecraft 动作条件生成上验证。"),
      memory: e("no", "论文把 3D representation as memory 留作未来工作。"),
      geometry: e("yes", "Angular + Scale Alignment 对齐冻结 VGGT teacher。"),
      closed: e("no", "只评估生成，不在代理闭环中执行。"),
    },
  },
  {
    paper: "WorldReel",
    venue: "CVPR 2026",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Fang_WorldReel_4D_Video_Generation_with_Consistent_Geometry_and_Motion_Modeling_CVPR_2026_paper.html",
    cells: {
      native: e("yes", "联合输出 RGB、pointmap、相机、光流与 3D scene flow。"),
      explicit: e("yes", "视频扩散建模 RGB 与 geo-motion latent 的联合分布。"),
      across: e("yes", "真实视频提供外观分布，合成数据提供 4D 标签。"),
      action: e("partial", "可受相机轨迹/输入图像控制，但非通用物理动作。"),
      memory: e("no", "固定时间窗；作者指出长时需要 streaming/causal diffusion。"),
      geometry: e("yes", "多任务头和静/动态正则有直接消融。"),
      closed: e("no", "没有闭环代理评测。"),
    },
  },
  {
    paper: "TesserAct",
    venue: "ICCV 2025",
    url: "https://openaccess.thecvf.com/content/ICCV2025/html/Zhen_Learning_4D_Embodied_World_Models_ICCV_2025_paper.html",
    cells: {
      native: e("partial", "先生成 RGB-D-N 视频，再通过几何优化升成单表面 4D。"),
      explicit: e("yes", "latent video diffusion 对未来 RGB-D-N 联合分布采样。"),
      across: e("yes", "在多套机器人视频上学习跨任务 prior。"),
      action: e("yes", "文本任务/机器人条件驱动未来交互。"),
      memory: e("no", "一次生成固定视频；无持久 belief。"),
      geometry: e("yes", "深度、法线一致性损失与 4D 重建。"),
      closed: e("partial", "生成的 4D 用于逆动力学与策略评测，但项目页建议多 seed 选优。"),
    },
  },
  {
    paper: "PointWorld",
    venue: "CVPR 2026 · Highlight",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Huang_PointWorld_Scaling_3D_World_Models_for_In-The-Wild_Robotic_Manipulation_CVPR_2026_paper.html",
    cells: {
      native: e("yes", "状态和动作都表示为世界中的 3D point flow。"),
      explicit: e("no", "预测均值位移与逐点 aleatoric 方差用于稳健损失，不等于采样多种未来。"),
      across: e("yes", "约 2M 轨迹、500 小时、跨机器人/仿真与真实数据。"),
      action: e("yes", "机器人 URDF 点流是 embodiment-agnostic 动作条件。"),
      memory: e("no", "输入假设观测时刻静止；作者指出动态初态需递归状态。"),
      geometry: e("yes", "稠密 3D track/point-flow 监督。"),
      closed: e("yes", "0.1 秒推理接入 MPPI/MPC，并在真实 Franka 上验证。"),
    },
  },
  {
    paper: "U4D",
    venue: "CVPR 2026",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Xu_U4D_Uncertainty-Aware_4D_World_Modeling_from_LiDAR_Sequences_CVPR_2026_paper.html",
    cells: {
      native: e("yes", "在 LiDAR range-view 中生成时序点云。"),
      explicit: e("yes", "两阶段 diffusion 可采样场景；但 uncertainty map 表示难度，不是完整后验校准。"),
      across: e("yes", "nuScenes/SemanticKITTI 场景分布。"),
      action: e("no", "没有驾驶动作条件。"),
      memory: e("no", "固定约 10 帧生成，长时随机误差累积。"),
      geometry: e("yes", "LiDAR 几何与时空 MoST 明确建模。"),
      closed: e("partial", "生成数据提升下游分割/校准，但未做规划闭环。"),
    },
  },
  {
    paper: "3WM",
    venue: "ICLR 2026",
    url: "https://iclr.cc/virtual/2026/poster/10009864",
    cells: {
      native: e("partial", "PGM 节点是 RGB/flow/camera patch；3D 从条件推断路径涌现。"),
      explicit: e("yes", "离散自回归 PGM 输出任意未观测节点的条件分布并可重复采样。"),
      across: e("yes", "同一 7B 模型联合多数据、多任务。"),
      action: e("yes", "稀疏/稠密 flow 和相机 token 作为几何变换 prompt。"),
      memory: e("no", "本体没有持久 3D scene belief。"),
      geometry: e("partial", "光流是因果中介；没有统一显式 3D 网格监督。"),
      closed: e("no", "验证 NVS、深度和对象编辑，没有机器人闭环。"),
    },
  },
  {
    paper: "P3Sim",
    venue: "CVPR 2026",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Lee_Perceptual_3D_Simulation_With_Physical_World_Modeling_CVPR_2026_paper.html",
    cells: {
      native: e("yes", "概率多模态变量通过 geometrizer 与 persistent 3D memory 落成场景。"),
      explicit: e("yes", "对缺失 RGB/depth/flow 节点预测条件分布，可产生多种未来。"),
      across: e("yes", "共享物理世界模型跨场景推断。"),
      action: e("yes", "部分 3D 变换/运动场作为条件。"),
      memory: e("yes", "记忆融合观测与预测几何，并剔除不一致/遮挡项。"),
      geometry: e("yes", "显式 projective geometry 构造 partial depth/flow 条件。"),
      closed: e("partial", "展示 NVS、操纵与动态预测系统，但无端到端机器人控制成功率。"),
    },
  },
  {
    paper: "LPWM",
    venue: "ICLR 2026 · Oral",
    url: "https://openreview.net/forum?id=lTaPtGiUUc",
    cells: {
      native: e("no", "latent particles 是 2D 关键点/框/遮罩与外观属性，不是原生 3D。"),
      explicit: e("yes", "逐粒子 latent action 高斯分布支持多模态随机 rollout。"),
      across: e("yes", "自监督视频预训练覆盖真实多对象数据。"),
      action: e("yes", "支持真实动作、语言和目标图像条件。"),
      memory: e("partial", "自回归粒子状态保持对象，但无全局 3D 地图。"),
      geometry: e("no", "没有 3D 几何监督。"),
      closed: e("partial", "用于 goal-conditioned imitation learning，但仍是 2D 表征。"),
    },
  },
];

export const d4rtCapabilityColumns = [
  { key: "recon", label: "3D Reconstruction", group: "Task" },
  { key: "dynamic", label: "Dynamic Correspondence", group: "Task" },
  { key: "flex", label: "Flexible Ref. Frames", group: "Functionality" },
  { key: "sparse", label: "Sparse Decoding", group: "Functionality" },
  { key: "global", label: "Global Context", group: "Architecture" },
  { key: "single", label: "Single Decoder", group: "Architecture" },
] as const;

export const d4rtCapabilityMatrix: MatrixRow[] = [
  ["MegaSaM", "CVPR 2025", "https://openaccess.thecvf.com/content/CVPR2025/html/Li_MegaSaM_Accurate_Fast_and_Robust_Structure_and_Motion_from_Casual_CVPR_2025_paper.html", [1, 0, 0, 0, 0, 0]],
  ["DUSt3R", "CVPR 2024", "https://openaccess.thecvf.com/content/CVPR2024/html/Wang_DUSt3R_Geometric_3D_Vision_Made_Easy_CVPR_2024_paper.html", [1, 0, 0, 0, 0, 0]],
  ["VGGT", "CVPR 2025", "https://openaccess.thecvf.com/content/CVPR2025/html/Wang_VGGT_Visual_Geometry_Grounded_Transformer_CVPR_2025_paper.html", [1, 0, 0, 0, 1, 0]],
  ["π³", "ICLR 2026", "https://arxiv.org/abs/2507.13347", [1, 0, 1, 0, 1, 0]],
  ["St4RTrack", "ICCV 2025", "https://arxiv.org/abs/2504.13152", [1, 1, 0, 0, 0, 0]],
  ["SpatialTrackerV2", "ICCV 2025", "https://openaccess.thecvf.com/content/ICCV2025/html/Xiao_SpatialTrackerV2_Advancing_3D_Point_Tracking_with_Explicit_Camera_Motion_ICCV_2025_paper.html", [1, 1, 0, 1, 1, 0]],
  ["D4RT", "CVPR 2026 · Best Paper", "https://openaccess.thecvf.com/content/CVPR2026/html/Zhang_Efficiently_Reconstructing_Dynamic_Scenes_One_D4RT_at_a_Time_CVPR_2026_paper.html", [1, 1, 1, 1, 1, 1]],
].map(([paper, venue, url, values]) => {
  const keys = d4rtCapabilityColumns.map((column) => column.key);
  return {
    paper: paper as string,
    venue: venue as string,
    url: url as string,
    cells: Object.fromEntries(
      keys.map((key, index) => [
        key,
        e((values as number[])[index] ? "yes" : "no", "该判定复核自 D4RT 原论文 Table 2。"),
      ]),
    ),
  };
});

export const dossiers: PaperDossier[] = [
  {
    id: "croco",
    title: "CroCo: Self-Supervised Pre-training for 3D Vision Tasks by Cross-View Completion",
    venue: "NeurIPS",
    year: 2022,
    branch: "前馈几何",
    relation: "直接继承",
    buildsOn: "MAE / masked image modeling",
    unique: "把单图遮挡补全改成“用另一视角补全当前视角”，迫使特征编码跨视图空间关系；最小新东西就是 cross-view completion 预训练目标。",
    evidence: "90% masking 的消融最佳；在同一 Habitat 数据上优于 MAE，并迁移到深度、法线、对应和姿态任务。",
    limitation: "训练主要来自合成室内图像对；对高层语义任务不占优。",
    readNext: "DUSt3R：看 CroCo 的双分支/交叉注意力怎样被改造成直接 3D 回归。",
    url: "https://papers.nips.cc/paper_files/paper/2022/hash/16e71d1a24b98a02c17b1be1f634f979-Abstract-Conference.html",
  },
  {
    id: "dust3r",
    title: "DUSt3R: Geometric 3D Vision Made Easy",
    venue: "CVPR",
    year: 2024,
    branch: "前馈几何",
    relation: "直接继承",
    buildsOn: "CroCo 架构与预训练",
    unique: "从未标定、无位姿图像对直接回归两张逐像素 pointmap，并都表达在第一相机坐标；把匹配、相机、深度和三角化压成一个 2D→3D 接口。",
    evidence: "消融显示 CroCo 预训练与高分辨率至关重要；在深度、相对姿态和重建上统一取得强结果。",
    limitation: "本体是两视图；N 视图仍需全局对齐优化，且静态/确定性假设明显。",
    readNext: "先读 MASt3R 看像素精度，再读 VGGT 看多视图联合，或读 MonST3R/DPM 看动态。",
    url: "https://openaccess.thecvf.com/content/CVPR2024/html/Wang_DUSt3R_Geometric_3D_Vision_Made_Easy_CVPR_2024_paper.html",
  },
  {
    id: "mast3r",
    title: "MASt3R: Grounding Image Matching in 3D with MASt3R",
    venue: "ECCV",
    year: 2024,
    branch: "前馈几何",
    relation: "直接继承",
    buildsOn: "DUSt3R",
    unique: "在 DUSt3R 上新增局部描述子/匹配头与 InfoNCE 损失，补上 pointmap 对视角稳健但像素匹配不够精确的问题。",
    evidence: "描述子匹配优于直接匹配 3D 点；联合 3D+matching 明显好于只训 matching；快速互惠匹配在 k=3000 时约 64× 加速。",
    limitation: "仍以图像对为核心；全局场景仍需对齐/优化。",
    readNext: "如果关心多视图，转 VGGT；如果关心在线状态，转 Spann3R。",
    url: "https://arxiv.org/abs/2406.09756",
  },
  {
    id: "spann3r",
    title: "Spann3R: 3D Reconstruction with Spatial Memory",
    venue: "3DV",
    year: 2025,
    branch: "持久记忆",
    relation: "直接继承",
    buildsOn: "DUSt3R 权重与 pointmap",
    unique: "用外部 working/long-term spatial memory 替代 DUSt3R 的测试时全局对齐，使每个新帧直接读出到全局坐标。",
    evidence: "去掉长期记忆后漂移迅速；约 4000 tokens 足够；在线推理约 65 FPS。",
    limitation: "无 bundle adjustment，长程/回环易漂移；静态世界、低分辨率和短序列训练限制明显。",
    readNext: "CUT3R：看静态 token memory 怎样变成可更新/可查询的 recurrent state。",
    url: "https://arxiv.org/abs/2408.16061",
  },
  {
    id: "monst3r",
    title: "MonST3R: A Simple Approach for Estimating Geometry in the Presence of Motion",
    venue: "ICLR",
    year: 2025,
    branch: "动态 4D",
    relation: "直接继承",
    buildsOn: "DUSt3R（作者称 Motion DUSt3R）",
    unique: "只微调 DUSt3R decoder+head，并混合少量动态深度数据，就让 pointmap 能适应运动场景；再以光流/静态掩码/平滑项做视频全局优化。",
    evidence: "Sintel ATE 从不微调的 0.354 降到 0.108；decoder+head 微调优于全量或只 head。",
    limitation: "对应仍依赖光流，长遮挡与滑窗对齐不稳；最佳配置仍需全局优化。",
    readNext: "Dynamic Point Maps：读它如何修正 MonST3R 缺少时间不变性的表征缺口。",
    url: "https://monst3r-project.github.io/",
  },
  {
    id: "dpm",
    title: "Dynamic Point Maps: A Versatile Representation for Dynamic 3D Reconstruction",
    venue: "ICCV",
    year: 2025,
    branch: "动态 4D",
    relation: "直接继承",
    buildsOn: "DUSt3R；以 MonST3R 为反例/对照",
    unique: "每张图不只预测当前时刻点图，而是预测两个时间的点图；固定相机和时间后恢复不变性，从坐标差直接得到 scene flow 与对应。",
    evidence: "对动态重建和 scene flow 明显优于 MonST3R；对象未来位置误差降低，旋转误差约降 40%。",
    limitation: "仍是两视图 DPM，视频需要额外融合；训练依赖合成/稀疏 4D 标签。",
    readNext: "V-DPM：它把 DPM 的时间不变性与 VGGT 的 N 视图联合合并。",
    url: "https://openaccess.thecvf.com/content/ICCV2025/html/Sucar_Dynamic_Point_Maps_A_Versatile_Representation_for_Dynamic_3D_Reconstruction_ICCV_2025_paper.html",
  },
  {
    id: "st4rtrack",
    title: "St4RTrack: Simultaneous 4D Reconstruction and Tracking in the World",
    venue: "ICCV",
    year: 2025,
    branch: "动态 4D",
    relation: "表征继承",
    buildsOn: "DUSt3R / MonST3R 风格双 pointmap",
    unique: "重新定义两张 pointmap 的时间含义：一张跟踪首帧物理内容到目标时刻，另一张重建目标帧；两者落在同一世界坐标。",
    evidence: "WorldTrack 同时评重建和跟踪；合成预训练后用可微 PnP reprojection loss 在无 4D 标签视频上适配。",
    limitation: "首帧—后帧成对处理，尺度错位、大相机运动与遮挡仍未彻底解决。",
    readNext: "D4RT：看同类重建+对应怎样变成一个稀疏 4D ray query。",
    url: "https://arxiv.org/abs/2504.13152",
  },
  {
    id: "cut3r",
    title: "CUT3R: Continuous 3D Perception Model with Persistent State",
    venue: "CVPR",
    year: 2025,
    branch: "持久记忆",
    relation: "问题延续",
    buildsOn: "DUSt3R/MASt3R 表征；解决 Spann3R 同类 memory 问题",
    unique: "引入 recurrent persistent 3D state、state update 和 state readout；还能以 raymap 查询未观测虚拟视角。",
    evidence: "在线相机位姿整体最佳，约 16.6 FPS；虚拟视图读出能补全未见结构。",
    limitation: "长序列仍漂移；确定性回归使外推几何模糊，作者明确建议生成式 formulation。",
    readNext: "Point4Cast：看持久状态从“重建过去/现在”推进到“查询未来”。",
    url: "https://openaccess.thecvf.com/content/CVPR2025/html/Wang_Continuous_3D_Perception_Model_with_Persistent_State_CVPR_2025_paper.html",
  },
  {
    id: "vggt",
    title: "VGGT: Visual Geometry Grounded Transformer",
    venue: "CVPR",
    year: 2025,
    honor: "Best Paper",
    branch: "前馈几何",
    relation: "表征继承",
    buildsOn: "DUSt3R 的共同坐标 pointmap；架构不是直接代码续作",
    unique: "用交替 frame-wise/global attention 在一次前馈中联合处理 1 到数百图像，并多任务预测相机、深度、pointmap 与跟踪特征。",
    evidence: "交替注意力优于 global-only/cross-attention；移除相机/深度/跟踪损失都会损害 pointmap，相机损失最关键。",
    limitation: "主模型为无序静态视图设计；无流式状态、度量尺度或多假设输出。",
    readNext: "D4RT 看输出接口变化；π³ 看固定参考帧问题；V-DPM 看动态扩展。",
    url: "https://openaccess.thecvf.com/content/CVPR2025/html/Wang_VGGT_Visual_Geometry_Grounded_Transformer_CVPR_2025_paper.html",
  },
  {
    id: "pi3",
    title: "π³: Permutation-Equivariant Visual Geometry Learning",
    venue: "ICLR",
    year: 2026,
    branch: "前馈几何",
    relation: "直接继承",
    buildsOn: "VGGT encoder/alternating attention 与预训练权重",
    unique: "去掉指定 reference view，预测尺度不变局部 pointmap 和仿射不变相机，使模型对输入视图排序严格等变。",
    evidence: "不同输入排列下指标标准差近零；在 DTU 上 VGGT accuracy std 0.033，π³ 约 0.003。",
    limitation: "不处理透明复杂光传输；细节不及扩散式方法，MLP 上采样在不确定区产生网格伪影。",
    readNext: "MapAnything：同样解耦局部几何与相机，但进一步加入 metric scale 与可选输入。",
    url: "https://arxiv.org/abs/2507.13347",
  },
  {
    id: "mapanything",
    title: "MapAnything: Universal Feed-Forward Metric 3D Reconstruction",
    venue: "3DV",
    year: 2026,
    branch: "前馈几何",
    relation: "问题延续",
    buildsOn: "VGGT/π³ 的多视图几何问题；CroCoV2 图像编码器",
    unique: "用 depth、local ray、pose、global metric scale 的因子化表征，统一带/不带相机、位姿、深度的 12+ 种度量 3D 任务。",
    evidence: "统一模型可匹配多种专用训练配置；几何输入与 metric scale 的消融支持因子化设计。",
    limitation: "不显式处理输入噪声/不确定性；输出仍与像素一一对应，限制大场景扩展；无动态。",
    readNext: "Any4D：它直接用 MapAnything 权重，把因子化 metric 表征扩到 scene flow 与多传感器。",
    url: "https://map-anything.github.io/",
  },
  {
    id: "vdpm",
    title: "V-DPM: 4D Video Reconstruction with Dynamic Point Maps",
    venue: "CVPR",
    year: 2026,
    branch: "动态 4D",
    relation: "直接继承",
    buildsOn: "Dynamic Point Maps + VGGT",
    unique: "把成对 DPM 扩成视频：保留 VGGT 的 time-variant pointmap，再加 time-conditioned decoder 生成固定目标时间的 time-invariant pointmap。",
    evidence: "两视图 4D 误差显著低于 DPM/St4RTrack，10 帧 dense track 也占优；用少量动态数据即可改造静态 VGGT。",
    limitation: "训练/评测规模受资源限制；长视频仍需重叠窗口和 bundle adjustment 融合。",
    readNext: "D4RT 比较“时间条件稠密 decoder”与“单点 4D ray query”的取舍。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Sucar_V-DPM_4D_Video_Reconstruction_with_Dynamic_Point_Maps_CVPR_2026_paper.html",
  },
  {
    id: "dynamicvggt",
    title: "DynamicVGGT: Learning Dynamic Point Maps for 4D Scene Reconstruction",
    venue: "CVPR",
    year: 2026,
    branch: "动态 4D",
    relation: "直接继承",
    buildsOn: "VGGT 权重 + DPM 概念",
    unique: "在 VGGT 中插入 motion-aware temporal attention，并用 future point head 学隐式位移、Dynamic 3DGS head 学显式高斯速度。",
    evidence: "加入 temporal attention+future head 后 KITTI accuracy 1.489→0.927；再加 3DGS head 到 0.901。",
    limitation: "主要面向自动驾驶短片；常速度高斯与短期 future point 不能代表开放式多未来。",
    readNext: "Any4D 看 metric/multimodal；Point4Cast 看真正 streaming forecast。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/He_DynamicVGGT_Learning_Dynamic_Point_Maps_for_4D_Scene_Reconstruction_in_CVPR_2026_paper.html",
  },
  {
    id: "any4d",
    title: "Any4D: Unified Feed-Forward Metric 4D Reconstruction",
    venue: "CVPR",
    year: 2026,
    branch: "动态 4D",
    relation: "直接继承",
    buildsOn: "MapAnything 初始化与因子化几何",
    unique: "把 4D 拆成局部相机坐标的 depth/ray 与全局坐标的 pose/scene flow/metric scale，并允许 RGB-D、IMU、Radar Doppler 任意组合。",
    evidence: "3D tracking/scene flow 误差常低 2–3×、速度最高快 15×；allocentric flow 表征消融最佳。",
    limitation: "所有 flow 从第一帧出发，目标需首帧可见；未建模传感器噪声与多未来。",
    readNext: "Point4Cast：Any4D 解决观测到的 N 帧，Point4Cast 再问未观测未来。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Karhade_Any4D_Unified_Feed-Forward_Metric_4D_Reconstruction_CVPR_2026_paper.html",
  },
  {
    id: "point4cast",
    title: "Point4Cast: Streaming Dynamic Scene Reconstruction and Forecasting",
    venue: "CVPR",
    year: 2026,
    branch: "持久记忆",
    relation: "直接继承",
    buildsOn: "VGGT 初始化；CUT3R/VGGT 均可作为 backbone",
    unique: "维护持续演化的 latent spacetime；每来一帧 update，给定任意已见 query frame 与过去/现在/未来时间 readout pointmap。",
    evidence: "重建与 1/10 帧未来预测均优于给基线加帧生成或 scene-flow 外推；FiLM 时间条件消融最佳。",
    limitation: "未来是单一预测；作者明确把 uncertainty modeling 列为下一步。",
    readNext: "U4D/3WM/P3Sim：从单未来转向可采样的不确定性。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Liu_Point4Cast_Streaming_Dynamic_Scene_Reconstruction_and_Forecasting_CVPR_2026_paper.html",
  },
  {
    id: "d4rt",
    title: "D4RT: Efficiently Reconstructing Dynamic Scenes One 4D Ray at a Time",
    venue: "CVPR",
    year: 2026,
    honor: "Best Paper",
    branch: "动态 4D",
    relation: "问题延续",
    buildsOn: "DUSt3R/VGGT 前馈范式；SRT 查询式 encoder-decoder；VideoMAEv2 初始化",
    unique: "一个 decoder 接收 (u,v,t_src,t_tgt,t_cam) 与局部 RGB patch，从全视频 latent 查询该物理点在目标时空的 3D 坐标。",
    evidence: "local RGB patch 消融带来显著提升；姿态速度超过 200 FPS，约 9× VGGT、100× MegaSaM。",
    limitation: "它不是 persistent streaming state，也不预测未观测未来；每个查询仍是确定性单点。",
    readNext: "若关心“多解 3D”，不要停在 D4RT：转 LRM limitation → TRELLIS/O-Voxel 或 3WM/P3Sim。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Zhang_Efficiently_Reconstructing_Dynamic_Scenes_One_D4RT_at_a_Time_CVPR_2026_paper.html",
  },
  {
    id: "lrm",
    title: "LRM: Large Reconstruction Model for Single Image to 3D",
    venue: "arXiv",
    year: 2023,
    branch: "3D 生成分布",
    relation: "问题延续",
    buildsOn: "single-image-to-3D encoder-decoder 与 triplane/NeRF",
    unique: "以 500M Transformer 在约百万对象上直接从单图预测 triplane-NeRF，把每对象优化改成跨对象摊销重建。",
    evidence: "5 秒输出对象 3D；遮挡部分能产生语义合理形状，证明跨对象 prior。",
    limitation: "论文明确指出单图本质多解但 LRM 是确定性的，遮挡区会平均多个 mode 而模糊。",
    readNext: "MVDream 或 TRELLIS：分别看“图像分布作为 3D prior”和“原生 3D latent 分布”。",
    url: "https://arxiv.org/abs/2311.04400",
  },
  {
    id: "mvdream",
    title: "MVDream: Multi-view Diffusion for 3D Generation",
    venue: "ICLR",
    year: 2024,
    branch: "3D 生成分布",
    relation: "问题延续",
    buildsOn: "Stable Diffusion + SDS / DreamFusion",
    unique: "把扩散分布从单图改成相机条件的联合多视图图像分布，既保留 2D 泛化又注入 3D 一致性。",
    evidence: "作为 SDS score prior 显著减少 Janus/不一致并提高稳定性；可做多视图 DreamBooth。",
    limitation: "分布仍在 2D 多视图，不是原生 3D；分辨率与风格受渲染训练集影响。",
    readNext: "TRELLIS：看生成变量从多视图像素真正移动到结构化 3D latent。",
    url: "https://proceedings.iclr.cc/paper_files/paper/2024/file/adbe936993aa7cf41e45054d8b72f183-Paper-Conference.pdf",
  },
  {
    id: "trellis",
    title: "TRELLIS: Structured 3D Latents for Scalable and Versatile 3D Generation",
    venue: "CVPR",
    year: 2025,
    honor: "Highlight",
    branch: "3D 生成分布",
    relation: "问题延续",
    buildsOn: "3D latent diffusion/flow 与稀疏 3D 表征",
    unique: "提出 SLAT：稀疏 3D 网格上的局部 latent 同时承载结构与外观，并用两阶段 rectified flow 先采样结构再采样属性。",
    evidence: "可从同一 latent 解码 RF、3DGS、mesh；rectified flow 优于 diffusion，模型放大持续改善。",
    limitation: "两阶段生成较慢；图像到 3D 会烘焙光照，缺少 PBR 材质分解。",
    readNext: "O-Voxel：同一团队直接修复拓扑、PBR 与压缩效率。",
    url: "https://trellis3d.github.io/",
  },
  {
    id: "ovoxel",
    title: "Native and Compact Structured Latents for 3D Generation (O-Voxel)",
    venue: "CVPR",
    year: 2026,
    honor: "Best Student Paper",
    branch: "3D 生成分布",
    relation: "直接继承",
    buildsOn: "TRELLIS/SLAT 生成 pipeline",
    unique: "用 O-Voxel 表达开放、非流形、封闭拓扑与 PBR 属性，再以 16× sparse compression VAE 把原生 3D 压成少量 latent tokens。",
    evidence: "去掉 residual AE 后几何误差增 69%；生成用户偏好约 66.5%，显著高于列出的资产模型。",
    limitation: "细于 voxel 的结构会 alias；偶发小孔；尚无 part-level 语义与拓扑图。",
    readNext: "FlashWorld/WorldReel：把静态资产分布延伸到场景与动态 4D。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Xiang_Native_and_Compact_Structured_Latents_for_3D_Generation_CVPR_2026_paper.html",
  },
  {
    id: "flashworld",
    title: "FlashWorld: High-quality 3D Scene Generation within Seconds",
    venue: "ICLR",
    year: 2026,
    honor: "Oral",
    branch: "3D 生成分布",
    relation: "问题延续",
    buildsOn: "多视图 diffusion、视频 diffusion、3DGS 与 distribution matching distillation",
    unique: "同一多视图扩散器设 MV-oriented/3D-oriented 两模式，再把高画质 MV 分布蒸馏到直接产 3DGS 的一致模式。",
    evidence: "消融显示 MV 模式重建噪声、3D 模式画面模糊，cross-mode post-training 同时改善；速度快 10–100×。",
    limitation: "目前是静态场景；论文把自回归与动态 4D 留作未来。",
    readNext: "WorldReel：它把 RGB、几何与运动放入同一个 4D 联合生成目标。",
    url: "https://arxiv.org/abs/2510.13678",
  },
  {
    id: "geometryforcing",
    title: "Geometry Forcing: Marrying Video Diffusion and 3D Representation",
    venue: "ICLR",
    year: 2026,
    branch: "3D 生成分布",
    relation: "表征继承",
    buildsOn: "自回归视频 diffusion + 冻结 VGGT teacher",
    unique: "不把几何作为外部输入，而用 Angular/Scale Alignment 把视频 diffusion 中间特征对齐到 VGGT 几何特征。",
    evidence: "VGGT 对齐优于 DINO 语义对齐；Angular+Scale FVD 243，直接 MSE 崩到 1648；也优于显式 ControlNet 几何条件。",
    limitation: "teacher 主要静态，显著运动泛化受限；仍会丢失透明/反射物体。",
    readNext: "WorldReel 比较“隐式几何对齐”与“显式联合生成 pointmap/flow”。",
    url: "https://arxiv.org/abs/2507.07982",
  },
  {
    id: "worldreel",
    title: "WorldReel: 4D Video Generation with Consistent Geometry and Motion Modeling",
    venue: "CVPR",
    year: 2026,
    branch: "3D 生成分布",
    relation: "问题延续",
    buildsOn: "视频 latent diffusion + depth/flow 几何先验",
    unique: "扩展视频 latent 为 appearance-agnostic geo-motion latent，并联合生成 RGB、pointmap、相机、光流、scene flow 与动态掩码。",
    evidence: "去掉 geo-motion latent 或联合训练均降低一致性；4D 指标与生成质量同时改善。",
    limitation: "依赖合成 4D 监督且仍有 domain gap；有限窗口在拓扑变化、重遮挡和快运动下失败。",
    readNext: "Point4Cast 看持久状态，或 3WM/P3Sim 看真正的条件分布与 belief。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Fang_WorldReel_4D_Video_Generation_with_Consistent_Geometry_and_Motion_Modeling_CVPR_2026_paper.html",
  },
  {
    id: "tesseract",
    title: "TesserAct: Learning 4D Embodied World Models",
    venue: "ICCV",
    year: 2025,
    branch: "物理世界模型",
    relation: "问题延续",
    buildsOn: "预训练 latent video diffusion + 机器人视频",
    unique: "把视频生成通道扩为 RGB-D-N，并以一致性损失和法线积分把采样视频转换为可用于动作规划的 4D scene。",
    evidence: "4D 表征提升逆动力学/动作规划成功率；几何与 novel-view 指标优于只生成 RGB 的视频模型。",
    limitation: "只能生成单表面；项目页展示物体消失、错误 affordance，并建议约 5 个随机 seed 选优。",
    readNext: "PointWorld：比较生成像素/深度与直接预测 3D point flow 的闭环效率。",
    url: "https://openaccess.thecvf.com/content/ICCV2025/html/Zhen_Learning_4D_Embodied_World_Models_ICCV_2025_paper.html",
  },
  {
    id: "pointworld",
    title: "PointWorld: Scaling 3D World Models for In-the-Wild Robotic Manipulation",
    venue: "CVPR",
    year: 2026,
    honor: "Highlight",
    branch: "物理世界模型",
    relation: "问题延续",
    buildsOn: "点云 backbone、3D tracking 与 model-predictive control",
    unique: "把场景状态与机器人动作统一成 3D point flow，让不同 embodiment 的动作可在同一几何空间条件化。",
    evidence: "约 2M 轨迹/500 小时；50M→1B 呈平滑 scaling；0.1 秒 rollout 接入 MPC，并在真实 Franka 零后训练执行多类任务。",
    limitation: "输入初态假设静止、无 appearance dynamics；逐点方差是稳健回归而不是多未来采样。",
    readNext: "3WM/P3Sim：若你要的是可采样 belief，而不只是快速确定性 dynamics。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Huang_PointWorld_Scaling_3D_World_Models_for_In-The-Wild_Robotic_Manipulation_CVPR_2026_paper.html",
  },
  {
    id: "u4d",
    title: "U4D: Uncertainty-Aware 4D World Modeling from LiDAR Sequences",
    venue: "CVPR",
    year: 2026,
    branch: "3D 生成分布",
    relation: "问题延续",
    buildsOn: "LiDAR diffusion / R2DM 与分割不确定性",
    unique: "先用分割熵挑出高不确定区域，第一阶段生成难区，第二阶段在难区条件下补全全场景；MoST 自适应融合时空分支。",
    evidence: "熵选区比 random/none 同时改善 FRD/FPD/ECE；adaptive MoST 优于串行、相加和 concat。",
    limitation: "这里的 uncertainty 首先是“哪里难”的结构先验，不等于校准的未来后验；超过约 10 帧误差明显累积。",
    readNext: "3WM/P3Sim：看对任意未观测变量直接定义条件分布的另一条路线。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Xu_U4D_Uncertainty-Aware_4D_World_Modeling_from_LiDAR_Sequences_CVPR_2026_paper.html",
  },
  {
    id: "3wm",
    title: "Unified 3D Scene Understanding Through Physical World Modeling (3WM)",
    venue: "ICLR",
    year: 2026,
    branch: "物理世界模型",
    relation: "问题延续",
    buildsOn: "autoregressive visual tokens + probabilistic graphical modeling",
    unique: "把 RGB、flow、camera 等局部 patch 当作 PGM 节点，用 pointer-content 的 local random-access sequence 学任意节点在任意已知子集下的条件分布。",
    evidence: "local+random 序列优于 raster/global；以 flow 为中介的 NVS/深度明显优于先生成 RGB 再求 flow。",
    limitation: "3D 是推断路径而非持久显式状态；运动模糊、对象复制、分割敏感且非实时。",
    readNext: "P3Sim：同一概率核心再加 geometrizer 与 persistent 3D memory。",
    url: "https://iclr.cc/virtual/2026/poster/10009864",
  },
  {
    id: "p3sim",
    title: "P3Sim: Perceptual 3D Simulation With Physical World Modeling",
    venue: "CVPR",
    year: 2026,
    branch: "物理世界模型",
    relation: "直接继承",
    buildsOn: "3WM/概率结构整合的 physical world model Ψ",
    unique: "在概率多模态 world model Ψ 外增加 geometrizer Γ 和 persistent scene memory μ，把部分 3D 变换变成 depth/flow 条件并持续融合成 belief。",
    evidence: "NVS 在 RE10K/LLFF/DTU 优于 ViewCrafter/SEVA；对象操作同时提高图像质量与 edit adherence。",
    limitation: "系统级扩展的独立消融与闭环机器人验证还不充分；仍继承生成模型的速度/伪影问题。",
    readNext: "把它与 PointWorld 并读：一个显式分布+belief，一个确定性 dynamics+真实 MPC。",
    url: "https://openaccess.thecvf.com/content/CVPR2026/html/Lee_Perceptual_3D_Simulation_With_Physical_World_Modeling_CVPR_2026_paper.html",
  },
  {
    id: "lpwm",
    title: "Latent Particle World Models",
    venue: "ICLR",
    year: 2026,
    honor: "Oral",
    branch: "物理世界模型",
    relation: "相邻参照",
    buildsOn: "DLP/DDLP object-centric video prediction",
    unique: "取消显式粒子跟踪，并为每个自发现粒子预测 latent action 分布，使同一初态能采样不同对象级未来。",
    evidence: "随机生成以 FVD 比较分布而非单 GT；多次 rollout 展示同一条件的多样合理运动，并用于 goal-conditioned imitation。",
    limitation: "主要是 2D 粒子/视频，不是 3D 状态；依赖小相机运动和重复对象，尚未证明通用 3D 世界建模。",
    readNext: "把它当作“多未来应该怎样验证”的参照，再反看 Point4Cast/PointWorld 缺少什么。",
    url: "https://openreview.net/forum?id=lTaPtGiUUc",
  },
];

export const branchCounts = Object.fromEntries(
  ["前馈几何", "动态 4D", "持久记忆", "3D 生成分布", "物理世界模型"].map((branch) => [
    branch,
    dossiers.filter((paper) => paper.branch === branch).length,
  ]),
);
